#!/bin/sh
set -e

# if /dev/log is either a named pipe or it was placed there accidentally then we remove it
# SEE: https://github.com/phusion/baseimage-docker/pull/25
[ ! -S /dev/log ] && rm -f /dev/log
[ ! -S /var/lib/syslog-ng/syslog-ng.ctl ] && rm -f /var/lib/syslog-ng/syslog-ng.ctl

SYSLOGNG_OPTS=""
[ -r /etc/default/syslog-ng ] && . /etc/default/syslog-ng
case "x$CONSOLE_LOG_LEVEL" in
    x[1-8])
        dmesg -n $CONSOLE_LOG_LEVEL
        ;;
    x)
        ;;
    *)
        echo "CONSOLE_LOG_LEVEL is of unaccepted value."
        ;;
esac
if [ ! -e /dev/xconsole ]; then
    mknod -m 640 /dev/xconsole p
    chown root:adm /dev/xconsole
    [ -x /sbin/restorecon ] && /sbin/restorecon $XCONSOLE
fi
syslog-ng -F -p /var/run/syslog-ng.pid $SYSLOGNG_OPTS &

exit 0
