#!/bin/bash
set -e

# open file descritors limit
# SEE https://github.com/docker/docker/issues/8231
ulimit -n 8192

SLAPD_CONFIG_PASSWORD=${SLAPD_CONFIG_PASSWORD:-admin}
SLAPD_PASSWORD=${SLAPD_PASSWORD:-secret}
SLAPD_ORGANIZATION=${SLAPD_ORGANIZATION:-Example}
SLAPD_DOMAIN=${SLAPD_DOMAIN:-example.com}

cat <<EOF | debconf-set-selections
slapd slapd/no_configuration boolean false
slapd slapd/password1 password $SLAPD_PASSWORD
slapd slapd/password2 password $SLAPD_PASSWORD
slapd shared/organization string $SLAPD_ORGANIZATION
slapd slapd/domain string $SLAPD_DOMAIN
slapd slapd/backend select HDB
slapd slapd/allow_ldap_v2 boolean false
slapd slapd/purge_database boolean false
slapd slapd/move_old_database boolean true
EOF
dpkg-reconfigure -f noninteractive slapd > /dev/null 2>&1

dc_str=""
IFS="."; declare -a parts=($SLAPD_DOMAIN)
for part in "${parts[@]}"; do
    dc_str="$dc_str,dc=$part"
done
base_str="BASE ${dc_str:1}"
sed -i "s/^#BASE.*/${base_str}/g" /etc/ldap/ldap.conf
if [ -n "$SLAPD_CONFIG_PASSWORD" ]; then
    password_hash=$(slappasswd -s "${SLAPD_CONFIG_PASSWORD}")
    sed_safe_password_hash=${password_hash//\//\\\/}
    slapcat -n0 -F /etc/ldap/slapd.d -l /tmp/config.ldif
    sed -i "s/\(olcRootDN: cn=admin,cn=config\)/\1\nolcRootPW: ${sed_safe_password_hash}/g" /tmp/config.ldif
    rm -rf /etc/ldap/slapd.d/*
    slapadd -n0 -F /etc/ldap/slapd.d -l /tmp/config.ldif > /dev/null 2>&1
    rm /tmp/config.ldif
fi

# execute additional schemas
if [ -n "$SLAPD_SCHEMAS" ]; then
    IFS=","; declare -a schemas=($SLAPD_SCHEMAS)
    for schema in "${schemas[@]}"; do
        slapadd -n0 -F /etc/ldap/slapd.d -l "/etc/ldap/schema/${schema}.ldif" > /dev/null 2>&1
    done
fi

# execute additional modules
if [ -n "$SLAPD_MODULES" ]; then
    IFS=","; declare -a modules=($SLAPD_MODULES)
    for module in "${modules[@]}"; do
         slapadd -n0 -F /etc/ldap/slapd.d -l "/etc/ldap/modules/${module}.ldif" > /dev/null 2>&1
    done
fi

chown -R openldap:openldap /etc/ldap/slapd.d
chown -R openldap:openldap /var/lib/ldap

exit 0
